services:
  auth-app:
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth2-db:5432/auth
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_REDIS_HOST=auth-redis
    container_name: auth-app
    depends_on:
      - db
      - redis
    ports:
       - "8080:8080"
    networks:
        - auth-app-network

  db:
    image: postgres:latest
    container_name: auth2-db
    restart: always
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
        - auth-app-network

  redis:
    image: redis:alpine3.20
    container_name: auth-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
        - auth-app-network

volumes:
  postgres_data:

networks:
  auth-app-network:
    driver: bridge
