spring.application.name=auth
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.data.redis.host=${SPRING_REDIS_HOST}
auth.jwt.secret=iasdfjijKJlkasjdf23.8su9df8u,2df
auth.jwt.expirationMs=600000
springdoc.swagger-ui.path=/api/auth/swagger-ui.html

cloud.aws.s3.endpoint=${S3_ENDPOINT:http://localhost:9000}
cloud.aws.s3.region=${S3_REGION:us-east-1}
cloud.aws.s3.bucket=${S3_BUCKET:myapp-bucket}
cloud.aws.credentials.access-key=${S3_ACCESS_KEY:minioadmin}
cloud.aws.credentials.secret-key=${S3_SECRET_KEY:minioadmin}
external.news.api-key=YOUR_API_KEY
external.news.url=https://newsapi.org/v2/top-headlines?country=us&apiKey=${external.news.api-key}
external.news.timeout=5000